---
- name: Delete PyYAML
  shell: "{{ item }}"
  loop:
    - "rm -rf /usr/lib/python3/dist-packages/yaml"
    - "rm -rf /usr/lib/python3/dist-packages/PyYAML-*"
    - "rm -rf /usr/lib/python{{ python3_version }}/site-packages/PyYAML-*"

- name: "Install {{ fts_ui_pip_package_name }}"
  pip:
    name: "{{ fts_ui_pip_package_name }}"
    executable: "pip{{ python3_version }}"
